# Generated by Django 5.2.7 on 2025-10-10 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_by_question', to='surveys.question'),
        ),
        migrations.AlterUniqueTogether(
            name='answerchoice',
            unique_together={('answer', 'choice')},
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('question', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('survey', 'order')},
        ),
    ]
